services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=<REDACTED_IP>:3001,<REDACTED_IP>,localhost,127.0.0.1
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3001:3000"
    restart: unless-stopped
